apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapp
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "addapp"
        dapr.io/port: "6000"
    spec:
      containers:
      - name: add
        image: localhost:32000/dapr-go-calculator-adder:registry
        ports:
        - containerPort: 6000
        imagePullPolicy: Always
