kind: Service
apiVersion: v1
metadata:
  name: dapr-go-calculator-react-frontend
  labels:
    app: dapr-go-calculator-react-frontend
spec:
  selector:
    app: dapr-go-calculator-react-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-go-calculator-react-frontend
  labels:
    app: dapr-go-calculator-react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-go-calculator-react-frontend
  template:
    metadata:
      labels:
        app: dapr-go-calculator-react-frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "dapr-go-calculator-react-frontend"
        dapr.io/port: "8080"
    spec:
      containers:
      - name: dapr-go-calculator-react-frontend
        image: localhost:32000/dapr-go-calculator-react-frontend:registry
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
